import {
  AmericanIcon,
  BritishIcon,
  CaribbeanIcon,
  ChineseIcon,
  FrenchIcon,
  IndianIcon,
  ItalianIcon,
  JapaneseIcon,
  MediterraneanIcon,
  MexicanIcon,
  SpanishIcon,
} from '@tastiest-io/tastiest-icons';
import { CuisineSymbol, ICuisine } from '@tastiest-io/tastiest-utils';
import {
  AmericaHeroDesktop,
  AmericaHeroMobile,
  BritainHeroDesktop,
  BritainHeroMobile,
  CaribbeanHeroDesktop,
  CaribbeanHeroMobile,
  ChinaHeroDesktop,
  ChinaHeroMobile,
  FranceHeroDesktop,
  FranceHeroMobile,
  IndiaHeroDesktop,
  IndiaHeroMobile,
  ItalyHeroDesktop,
  ItalyHeroMobile,
  JapanHeroDesktop,
  JapanHeroMobile,
  MediterraneanHeroDesktop,
  MediterraneanHeroMobile,
  MexicoHeroDesktop,
  MexicoHeroMobile,
  SpainHeroDesktop,
  SpainHeroMobile,
} from 'public/assets/cuisine-pages';

const CUISINES = {
  [CuisineSymbol.ITALIAN]: {
    name: 'Italian',
    href: '/italian',
    svg: ItalianIcon,
    pageSvgDesktop: ItalyHeroDesktop,
    pageSvgMobile: ItalyHeroMobile,
    popularity: 1103,
  },
  [CuisineSymbol.FRENCH]: {
    name: 'French',
    href: '/french',
    svg: FrenchIcon,
    pageSvgDesktop: FranceHeroDesktop,
    pageSvgMobile: FranceHeroMobile,
    popularity: 1337,
  },
  [CuisineSymbol.JAPANESE]: {
    name: 'Japanese',
    href: '/japanese',
    svg: JapaneseIcon,
    pageSvgDesktop: JapanHeroDesktop,
    pageSvgMobile: JapanHeroMobile,
    popularity: 2147,
  },
  [CuisineSymbol.CHINESE]: {
    name: 'Chinese',
    href: '/chinese',
    svg: ChineseIcon,
    pageSvgDesktop: ChinaHeroDesktop,
    pageSvgMobile: ChinaHeroMobile,
    popularity: 3333,
  },
  [CuisineSymbol.INDIAN]: {
    name: 'Indian',
    href: '/indian',
    svg: IndianIcon,
    pageSvgDesktop: IndiaHeroDesktop,
    pageSvgMobile: IndiaHeroMobile,
    popularity: 4096,
  },
  [CuisineSymbol.SPANISH]: {
    name: 'Spanish',
    href: '/spanish',
    svg: SpanishIcon,
    pageSvgDesktop: SpainHeroDesktop,
    pageSvgMobile: SpainHeroMobile,
    popularity: 13,
  },
  [CuisineSymbol.BRITISH]: {
    name: 'British',
    href: '/british',
    svg: BritishIcon,
    pageSvgDesktop: BritainHeroDesktop,
    pageSvgMobile: BritainHeroMobile,
    popularity: 11,
  },
  [CuisineSymbol.AMERICAN]: {
    name: 'American',
    href: '/america',
    svg: AmericanIcon,
    pageSvgDesktop: AmericaHeroDesktop,
    pageSvgMobile: AmericaHeroMobile,
    popularity: 400,
  },
  [CuisineSymbol.MEXICAN]: {
    name: 'Mexican',
    href: '/mexican',
    svg: MexicanIcon,
    pageSvgDesktop: MexicoHeroDesktop,
    pageSvgMobile: MexicoHeroMobile,
    popularity: 903,
  },
  [CuisineSymbol.CARIBBEAN]: {
    name: 'Caribbean',
    href: '/caribbean',
    svg: CaribbeanIcon,
    pageSvgDesktop: CaribbeanHeroDesktop,
    pageSvgMobile: CaribbeanHeroMobile,
    popularity: 903,
  },
  [CuisineSymbol.MEDITERRANEAN]: {
    name: 'Mediterranean',
    href: '/mediterranean',
    svg: MediterraneanIcon,
    pageSvgDesktop: MediterraneanHeroDesktop,
    pageSvgMobile: MediterraneanHeroMobile,
    popularity: 543,
  },
} as { [name: string]: ICuisine };

export default CUISINES;
