import {
  AmericanIcon,
  BritishIcon,
  CaribbeanIcon,
  ChineseIcon,
  FrenchIcon,
  IndianIcon,
  ItalianIcon,
  JapaneseIcon,
  MediterraneanIcon,
  MexicanIcon,
  SpanishIcon,
} from '@tastiest-io/tastiest-icons';
import { CuisineSymbol, ICuisine } from '@tastiest-io/tastiest-utils';
import {
  AmericaHero,
  BritainHero,
  CaribbeanDesktopHero,
  CaribbeanMobileHero,
  ChinaHero,
  FranceHero,
  IndiaHero,
  ItalyHero,
  JapanHero,
  MediterraneanHero,
  MexicoHero,
  SpainHero,
} from 'public/assets/cuisine-pages';

const CUISINES = {
  [CuisineSymbol.ITALIAN]: {
    name: 'Italian',
    href: '/italian',
    svg: ItalianIcon,
    pageSvg: ItalyHero,
    popularity: 1103,
  },
  [CuisineSymbol.FRENCH]: {
    name: 'French',
    href: '/french',
    svg: FrenchIcon,
    pageSvg: FranceHero,
    popularity: 1337,
  },
  [CuisineSymbol.JAPANESE]: {
    name: 'Japanese',
    href: '/japanese',
    svg: JapaneseIcon,
    pageSvg: JapanHero,
    popularity: 2147,
  },
  [CuisineSymbol.CHINESE]: {
    name: 'Chinese',
    href: '/chinese',
    svg: ChineseIcon,
    pageSvg: ChinaHero,
    popularity: 3333,
  },
  [CuisineSymbol.INDIAN]: {
    name: 'Indian',
    href: '/indian',
    svg: IndianIcon,
    pageSvg: IndiaHero,
    popularity: 4096,
  },
  [CuisineSymbol.SPANISH]: {
    name: 'Spanish',
    href: '/spanish',
    svg: SpanishIcon,
    pageSvg: SpainHero,
    popularity: 13,
  },
  [CuisineSymbol.BRITISH]: {
    name: 'British',
    href: '/british',
    svg: BritishIcon,
    pageSvg: BritainHero,
    popularity: 11,
  },
  [CuisineSymbol.AMERICAN]: {
    name: 'American',
    href: '/america',
    svg: AmericanIcon,
    pageSvg: AmericaHero,
    popularity: 400,
  },
  [CuisineSymbol.MEXICAN]: {
    name: 'Mexican',
    href: '/mexican',
    svg: MexicanIcon,
    pageSvg: MexicoHero,
    popularity: 903,
  },
  [CuisineSymbol.CARIBBEAN]: {
    name: 'Caribbean',
    href: '/caribbean',
    svg: CaribbeanIcon,
    pageSvgDesktop: CaribbeanDesktopHero,
    pageSvgMobile: CaribbeanMobileHero,
    popularity: 903,
  },
  [CuisineSymbol.MEDITERRANEAN]: {
    name: 'Mediterranean',
    href: '/mediterranean',
    svg: MediterraneanIcon,
    pageSvg: MediterraneanHero,
    popularity: 543,
  },
} as { [name: string]: ICuisine };

export default CUISINES;
