const UI = {
  MOBILE_BREAKPOINT: 500,
  TABLET_BREAKPOINT: 715,
  DESKTOP_BREAKPOINT: 1100,
  MAX_CONTENT_WIDTH: 1300,
  PAGE_CONTAINED_PADDING_VW: 5,

  USER_QUERY_404_MAX_LEN: 500,

  ARTICLE: {
    TITLE_MAX_WIDTH_REM: 29,
  },
};

export default UI;
